version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: java -jar ./tgbot-app-master-degree-0.0.1.jar
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
    environment:
      - MONGODB_DB=reports
      - MONGODB_URL=mongodb:27017
      - MONGODB_USERNAME=nikitadev
      - MONGODB_PASSWORD=mongopassword
      - BOT_TOKEN=5973162662:AAEu1iTH4fYwFgyPT6RDPUsYFK-5y4Xn_qI
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: reports
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro